### ISSUE TITLE
Problems with LXQtTranslateDesktop.cmake

### ISSUE THREAD

**Issue by adjamhub** [lxqt/lxqt-build-tools#63]
I'm having errors with LXQtTranslateDesktop.cmake against cmake 3.19. It everywhere fails with the following error:

CMake Error at /usr/share/cmake/lxqt-build-tools/modules/LXQtTranslateDesktop.cmake:62 (string):
  string sub-command REPLACE requires at least four arguments.
Call Stack (most recent call first):
  some/CMakeLists.txt (lxqt_translate_desktop)

It is obviously a problem with lxqt_translate_desktop macro.

##### Steps to Reproduce (for bugs)

1. install lxqt-build-tools 0.8.0
2. install cmake 3.19
3. try compiling something from lxqt project

##### System Information

* Distribution & Version: ArchLinux
* Kernel: 5.10
* Qt Version: 5.15
* Package version: 0.8.0

**Comment by tsujan** [comment]
Not reproducible.

@luis-pereira?

**Comment by palinek** [comment]
Please, try to use latest git lxqt-build-tools when trying to compile latest git components. There was recent update for translation of the desktop files.

**Comment by luis-pereira** [comment]
Not reproducible.

**Comment by adjamhub** [comment]
I can confirm everything works with latest git components. Thanks.
