### ISSUE TITLE
lxqt-desktop.desktop file installed in wrong location

### ISSUE THREAD

**Issue by cepamoi** [lxqt/lxqt-build-tools#71]
##### Expected Behavior
I am installing pcmanfm-qt from the source code.
I'm not sure where the file lxqt-desktop.desktop should be installed.
But I guess it should be in the directory passed with CMAKE_INSTALL_PREFIX.

##### Current Behavior
The file lxqt-desktop.desktop file is installed in a wrong location.

##### Possible Solution
Try to install lxqt-desktop.desktop in the directory passed with CMAKE_INSTALL_PREFIX.

##### Steps to Reproduce (for bugs)
First attempt with Qt 5.15.2 installed in a user directory:
```
cmake -DCMAKE_INSTALL_PREFIX=/home/julien/pcmanfm-qt-install ..
...
make install
...
-- Installing: /space/julien/pcmanfm-qt/install/Qt-5.15.2/etc/xdg/autostart/lxqt-desktop.desktop
```
/space/julien/pcmanfm-qt/install/Qt-5.15.2 is my Qt installation.
Why is the file lxqt-desktop.desktop installed with my Qt installation?

Another attempt with Qt 5.12.8 from the Ubuntu installation:
```
cmake -DCMAKE_INSTALL_PREFIX=/space/julien/pcmanfm-qt/test5.12/install ..
...
make install
...
-- Installing: /etc/xdg/autostart/lxqt-desktop.desktop
CMake Error at autostart/cmake_install.cmake:49 (file):
  file INSTALL cannot copy file
  "/space/julien/pcmanfm-qt/test5.12/pcmanfm-qt-1.0.0/build/autostart/lxqt-desktop.desktop"
  to "/etc/xdg/autostart/lxqt-desktop.desktop": Permission denied.
Call Stack (most recent call first):
  cmake_install.cmake:47 (include)

```
Why is the file lxqt-desktop.desktop installed in /etc? I requested pcmanfm-qt to be installed in a user directory.

##### System Information
* PcManFm-qt version: 1.0.0
* Distribution & Version: Kubuntu 20.04
* Qt Version: 5.15.2 / 5.12.8
* liblxqt Version: 1.0.0

**Comment by tsujan** [comment]
Not my area of expertise but `FindInstallConfigPath.cmake` says about `LXQT_ETC_XDG_DIR`, "You can set it manually with -DLXQT_ETC_XDG_DIR=<value>". If I'm not mistaken, since it isn't set in the compilation of `lxqt-build-tools`. it'll be detected automatically based on `QT_QMAKE_EXECUTABLE`.

**Comment by cepamoi** [comment]
Installing the lxqt-desktop.desktop file based on QT_QMAKE_EXECUTABLE indeed explains the current behavior.
But I'm not sure this is the correct behavior.
Usually, XDG desktop files are installed in /usr/share/applications or to $HOME/.local/share/applications.
Why do pcmanfm-qt or lxqt-build-tools not follow this convention?

**Comment by tsujan** [comment]
> Usually, XDG desktop files are installed in /usr/share/applications

This is about auto-start.
