### ISSUE TITLE
LXQT_ETC_XDG_DIR definition seems ignored on command line

### ISSUE THREAD

**Issue by redtide** [lxqt/lxqt-build-tools#72]
In my `picom-conf` fork I'm still using the original `compton-conf`' lxqt-build-tools setup for translations.
I added a Github Actions workflow to test builds and produce artifacts for download, but when I look into the produced archive, I get a strange path instead `/etc/xdg/autostart`, where it should install the `.desktop` file, I guess this because I have a custom Qt install because the version in the GHA Ubuntu image is too old for the project, which uses lxqt-build-tools 0.8.0, which in turns requires Qt 5.15 and the Ubuntu 20.04 image has 5.12.
At this point I saw that `LXQT_ETC_XDG_DIR` is set in `cmake/FindInstallConfigPath.cmake` and that it can be also set manually.
I tried locally on my Archlinux system, but it seems that it gets ignored for some reason I don't understand, so what I am doing wrong?

##### Expected Behavior
`LXQT_ETC_XDG_DIR` should use the manual setting when defined from CMake command line.

##### Current Behavior
It still resolve as `/etc/xdg/`.

##### Possible Solution
No idea, I don't see any issue in the build tools script.

##### Steps to Reproduce (for bugs)

1. Test it with an application using lxqt-build-tools, in my case `picom-conf`
2. Run CMake to configure, build and install the files, I did as following:
```sh
cmake -DCMAKE_INSTALL_PREFIX="/usr" -DCMAKE_BUILD_TYPE="Release" -DLXQT_ETC_XDG_DIR="/abcd" -B buildtest
cmake --build buildtest --config Release
DESTDIR="$(pwd)/installtest" cmake --build buildtest --target install
```

##### Context

See description.

##### System Information

* Distribution & Version: Archlinux
* Kernel: 5.14.16-arch1-1
* Qt Version: 5.15.2
* Package version: 0.10.0

**Comment by tsujan** [comment]
Please read https://github.com/lxqt/lxqt-build-tools/issues/71#issuecomment-967738468

You could use https://github.com/lxqt/lxqt/discussions for questions.

**Comment by redtide** [comment]
This was not a question, it is not set specifying it from the command line as the comment in the CMake module say, it looks like a bug to me instead, unless I did something wrong somewhere else, which should be made clear and that comment does not.

**Comment by tsujan** [comment]
I made the same mistake in https://github.com/lxqt/lxqt-build-tools/issues/71#issuecomment-967734094 (→ the sentence that's stricken through). Whether a warning should have been shown for my mistake or not is another question but it isn't a bug. All LXQt apps should refer to the same place, which can be be changed only for all of them.

**Comment by palinek** [comment]
The `LXQT_ETC_XDG_DIR` is defined in build time of lxqt-build-tools component and as such is generated into installed file [`LXQtConfigVars.cmake`](https://github.com/lxqt/lxqt-build-tools/blob/master/cmake/LXQtConfigVars.cmake.in#L25).

As you are not building your own lxqt-build-tools package, but rather using a prebuilt one, there is no way to override the `LXQT_ETC_XDG_DIR` while compiling your package.

**Comment by redtide** [comment]
Thank you, it wasn't clear to me this before, so I removed the lxqt build tools dependency, kept 2 cmake modules for the translations and using `$CMAKE_INSTALL_FULL_SYSCONFDIR` instead.
It should be nice to make the script comment clear about being a build time variable and cannot be modified.
