### ISSUE TITLE
GLIB is not found

### ISSUE THREAD

**Issue by papoteur-mga** [lxqt/lxqt-build-tools#81]
Trying to build libqtxdg, I get this error:
```
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find GLIB (missing: GLIB_GIO_UNIX_INCLUDE_DIR) (found suitable
  version "2.74.0", minimum required is "2.41.0")
```
However, lib64glib2.0_0-2.74.0-1.mga9.x86_64 is installed
Here is the content of /usr/include/gio-unix-2.0/gio/
`gdesktopappinfo.h  gfiledescriptorbased.h  gunixfdmessage.h  gunixinputstream.h  gunixmounts.h  gunixoutputstream.h`

##### Expected Behavior
GLIB should be found

##### Current Behavior
GLIB is not found

##### Possible Solution
Check another file than `gunixfdlist.h`
##### System Information
* Distribution & Version: Mageia cauldron
* Package version: lxqt-build-tools-0.11.0

**Comment by tsujan** [comment]
Already reported and fixed in https://github.com/lxqt/lxqt-build-tools/commit/4991811d9212ec1176af6d1cbe88aa37efad4836
